### PR TITLE
use id attribute as alternative to data-bespoke-hash

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
As an alternative to the `data-bespoke-hash` attribute, this patch enables the bespoke-hash plugin to look at the `id` attribute on a slide.

If you don't want to activate this feature by default, I'd be okay to hide it behind an option (e.g., `{ byId: true }`.

**Comment by mojavelinux** [comment]
@markdalgleish is there a reason I should know about that you decide to use the data-bespoke-hash attribute instead of the id attribute for named routing? Knowing that reason would help me understand if we need to make this an option.

**Comment by mojavelinux** [comment]
@hsablonniere could you merge this and make a new release?

**Comment by hsablonniere** [comment]
@mojavelinux LGTM!

**Comment by hsablonniere** [comment]
Version here: https://github.com/bespokejs/bespoke-hash/releases/tag/v1.1.0

**Pull request merged**
